RedBadge/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using RedBadge.Models.GameModels;
using RedBadge.Services.Game;


namespace RedBadge.Controllers
{
    [Route("[controller]")]
    public class GameController : Controller
    {
        private IGameService _gameService;

        public GameController(IGameService gameService)
        {
            _gameService = gameService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _gameService.GetAllGamesAsync());
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await _gameService.GetGameByIdAsync(id));
        }

        [HttpGet]
        [Route("Post")]
        public async Task<IActionResult> Post()
        {
            return View();
        }

        [HttpPost]
        [Route("Post")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Post(GameCreate game)
        {
            if(!ModelState.IsValid)return BadRequest(ModelState);
            if(await _gameService.CreateGameAsync(game))
                return RedirectToAction(nameof(Index));
            else
                return View(game);
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var game = await _gameService.GetGameByIdAsync(id);
            var gameEdit = new GameEdit
            {
                Id = game.Id,
                Name = game.Name,
            };
            return View(gameEdit);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, GameEdit gameModel)
        {
            if (id!=gameModel.Id) return BadRequest("Invalid ID");
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _gameService.UpdateGameAsync(id, gameModel))
                return RedirectToAction(nameof(Index));
            else
                return View(gameModel);
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var game = await _gameService.GetGameByIdAsync(id.Value);
            return View(game);
        }

        [HttpPost]
        [Route("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var isSuccessful = await _gameService.DeleteGameAsync(id);
            if (isSuccessful)
                return RedirectToAction(nameof(Index));
            else
                return UnprocessableEntity();
        }
    }
}

RedBadge/Controllers/OccasionController.cs
using Microsoft.AspNetCore.Mvc;
using RedBadge.Models.OccasionModels;
using RedBadge.Services.Occasion;
using RedBadge.Services.Player;

namespace RedBadge.Controllers
{
    public class OccasionController : Controller
    {
        private IOccasionService _occasionService;
        
        public OccasionController(IOccasionService occasionService)
        {
            _occasionService = occasionService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _occasionService.GetAllOccasionsAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            return View(await _occasionService.GetOccasionByIdAsync(id));
        }

        [HttpGet]
        public async Task<IActionResult> Post()
        {
            return View();
        }


        [HttpPost]
        [ActionName("Post")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostOccasion(OccasionCreate model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _occasionService.CreateOccasionAsync(model))
                return RedirectToAction(nameof(Index));
            else
                return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var occasion = await _occasionService.GetOccasionByIdAsync(id);
            var occasionEdit = new OccasionEdit
            {
                Id = occasion.Id,
                Name = occasion.Name,
            };
            return View(occasionEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OccasionEdit occasionModel)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _occasionService.UpdateOccasionAsync(id, occasionModel))
                return RedirectToAction(nameof(Index));
            else
                return View(occasionModel);
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var occasion = await _occasionService.GetOccasionByIdAsync(id.Value);
            return View(occasion);
        }

        [HttpPost]
        [Route("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var isSuccessful = await _occasionService.DeleteOccasionAsync(id);
            if (isSuccessful)
                return RedirectToAction(nameof(Index));
            else
                return UnprocessableEntity();
        }
    }
}

RedBadge/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using RedBadge.Models.PlayerModels;
using RedBadge.Services.Player;

namespace RedBadge.Controllers
{
    [Route("[controller]")]
    public class PlayerController : Controller
    {
        private IPlayerService _playerService;

        public PlayerController(IPlayerService playerService)
        {
            _playerService = playerService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _playerService.GetAllPlayersAsync());
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await _playerService.GetPlayerByIdAsync(id));
        }

        [HttpGet]
        [Route("Post")]
        public async Task<IActionResult> Post()
        {
            return View();
        }

        [HttpPost]
        [Route("Post")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Post(PlayerCreate model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _playerService.CreatePlayerAsync(model))
                return RedirectToAction(nameof(Index));
            else
                return View(model);
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var player = await _playerService.GetPlayerByIdAsync(id);
            var playerEdit = new PlayerEdit
            {
                Id = player.Id,
                Name = player.Name,
            };
            return View(playerEdit);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PlayerEdit playerModel)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _playerService.UpdatePlayerAsync(id, playerModel))
                return RedirectToAction(nameof(Index));
            else
                return View(playerModel);
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var player = await _playerService.GetPlayerByIdAsync(id.Value);
            return View(player);
        }

        [HttpPost]
        [Route("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var isSuccessful = await _playerService.DeletePlayerAsync(id);
            if(isSuccessful)
                return RedirectToAction(nameof(Index));
            else
                return UnprocessableEntity();
        }
    }
}

RedBadge/Controllers/RankController.cs
using Microsoft.AspNetCore.Mvc;
using RedBadge.Models.PlayerModels;
using RedBadge.Models.RankModels;
using RedBadge.Services.Rank;

namespace RedBadge.Controllers
{
        public class RankController : Controller
        {
            private IRankService _rankService;

            public RankController(IRankService rankService)
            {
                _rankService = rankService;
            }

            [HttpGet]
            public async Task<IActionResult> Index()
            {
                return View(await _rankService.GetAllRanksAsync());
            }

            [HttpGet]
            public async Task<IActionResult> Details(int id)
            {
                return View(await _rankService.GetRankByIdAsync(id));
            }

            [HttpGet]
            [Route("Post")]
            public async Task<IActionResult> Post()
            {
                return View();
            }

            [HttpPost]
            [Route("Post")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Post(RankCreate model)
            {
                if (!ModelState.IsValid) return BadRequest(ModelState);
                if (await _rankService.CreateRankAsync(model))
                    return RedirectToAction(nameof(Index));
                else
                    return View(model);
            }

            [HttpGet]
            [Route("Edit/{id}")]
            public async Task<IActionResult> Edit(int id)
            {
                var rank = await _rankService.GetRankByIdAsync(id);
                var rankEdit = new RankEdit
                {
                    Id = rank.Id,
                    RankName = rank.RankName,
                };
                return View(rankEdit);
            }

            [HttpPost]
            [Route("Edit/{id}")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, RankEdit rankModel)
            {
                if (!ModelState.IsValid) return BadRequest(ModelState);
                if (await _rankService.UpdateRankAsync(id, rankModel))
                    return RedirectToAction(nameof(Index));
                else
                    return View(rankModel);
            }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var rank = await _rankService.GetRankByIdAsync(id.Value);
            return View(rank);
        }

        [HttpPost]
        //[Route("Delete/{id}")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var isSuccessful = await _rankService.DeleteRankAsync(id);
            if (isSuccessful)
                return RedirectToAction(nameof(Index));
            else
                return UnprocessableEntity();
        }
    }
}

RedBadge/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["title"] - redbadge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/redbadge.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/RedBadge.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark mb-3 navbar-expand-lg">
            <a class="navbar-brand" asp-area="" asp-controller="home" asp-action="index">frENDr</a>
                <button class="navbar-toggler" id="nav-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="IndividualResults" asp-action="Index">Results</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Occasion" asp-action="Index">Occasions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Rank" asp-action="Index">Ranks</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - frENDr - <a asp-area="" asp-controller="home" asp-action="privacy">privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>