RedBadge/Controllers/IndividualResultsController.cs
using Microsoft.AspNetCore.Mvc;
using RedBadge.Models.IndividualResultsModels;
using RedBadge.Services.IndividualResults;

namespace RedBadge.Controllers
{
    [Route("[controller]")]
    public class IndividualResultsController : Controller
    {
        private IIRService _iRService;

        public IndividualResultsController(IIRService iRService)
        {
            _iRService = iRService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _iRService.GetAllIRAsync());
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Details(int iRId)
        {
            return View(await _iRService.GetIRByIdAsync(iRId));
        }

        [HttpGet]
        [Route("Post")]
        public async Task<IActionResult> Post()
        {
            return View(await _iRService.GetIRCreateAsync());
        }

        [HttpPost]
        [Route("Post")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Post(IRCreate model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _iRService.CreateIRAsync(model))
                return RedirectToAction(nameof(Index));
            else
                return View(model);
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public async Task<IActionResult> Edit(int iRId)
        {
            var iR = await _iRService.GetIRByIdAsync(iRId);
            var iREdit = new IREdit
            {
                Id = iR.Id,
            };
            return View(iREdit);
        }

        [HttpPost]
        [Route("Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IREdit iRModel)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            if (await _iRService.UpdateIRAsync(iRModel))
                return RedirectToAction(nameof(Index));
            else
                return View(iRModel);
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int? iRId)
        {
            var iR = await _iRService.GetIRByIdAsync(iRId.Value);
            return View(iR);
        }

        [HttpGet]
        [Route("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int iRId)
        {
            var isSuccessful = await _iRService.DeleteIRAsync(iRId);
            if (isSuccessful)
                return RedirectToAction(nameof(Index));
            else
                return UnprocessableEntity();
        }
    }
}

RedBadge/Views/IndividualResults/Index.cshtml
@model IEnumerable<RedBadge.Models.IndividualResultsModels.IRListItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Results Records</h1>

    @Html.ActionLink("Add Results", "Post", "IndividualResults")

<div>
<div>
<ul>

@{
    String OccasionCache = "";
}

@foreach (var item in Model) {
    <text>
    @if (item.OccasionName != OccasionCache)
    {
        OccasionCache = item.OccasionName;
        @Html.Raw("</ul></div></div>")

        <text>
            <div class="card mb-4">
                <div class="card-body">
        <h5 class="card-title">@Html.DisplayFor(modelItem => item.OccasionName)</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Html.DisplayFor(modelItem => item.GameName)</h6>
        <ul class="list-group list-group-flush">

        </text>
    }
    </text>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                        @Html.DisplayFor(modelItem => item.PlayerName)
                    <span class="badge badge-pill badge-secondary">@Html.DisplayFor(modelItem => item.RankName)</span>
                    </li>
}

RedBadge/Views/IndividualResults/Post.cshtml
@model RedBadge.Models.IndividualResultsModels.IRCreate

@{
    ViewData["Title"] = "Create Results";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Home">Results</a></li>
        <li class="breadcrumb-item active" aria-current="page">
            Create Results 
        </li>
    </ol>
</nav>

<div class="card mt-3">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form asp-action="Post">
                    <div class="form-group">
                        <select asp-for="GameId">
                            @foreach (var option in Model.GameOptions)
                            {
                                Console.WriteLine(option.Name);
                                <option value=@option.Id>@option.Name</option>
                            }
                        </select><select asp-for="PlayerId">
                            @foreach (var option in Model.PlayerOptions)
                            {
                                Console.WriteLine(option.Name);
                                <option value=@option.Id>@option.Name</option>
                            }
                        </select><select asp-for="OccasionId">
                            @foreach (var option in Model.OccasionOptions)
                            {
                                Console.WriteLine(option.Name);
                                <option value=@option.Id>@option.Name</option>
                            }
                        </select><select asp-for="RankId">
                            @foreach (var option in Model.RankOptions)
                            {
                                Console.WriteLine(option.RankName);
                                <option value=@option.Id>@option.RankName</option>
                            }
                        </select>
                    </div>
                    <div class="form-group mt-2">
                        <input type="submit" value="Add" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>